### ISSUE TITLE
Question: time clock and time code examples

### ISSUE THREAD

**Issue by oubiwann** [gbevin/SendMIDI#29]
First off, let me just say -- well done! Really nicely designed CLI tools for MIDI. Absolutely the best I've ever seen. I'm so grateful you've implemented support for catpuring `stdin` with `--`, too -- that's how we're going to be integrating with SendMIDI in Erlang/OTP.

Enough, effusing! Question time ;-)

I have no experience with MIDI time clock data or time codes but would love to use these so that when I send to the
* DAW from our software (a dialect of Erlang which will be managing the `sendmidi` and `receivemidi` OS processes) the DAW will sync all the VST soft synths 
* iPad Moog synths over USB MIDI (IDAM), they get synced with the generative MIDI we're pumping into `sendmidi` (e.g., our implementation of sequencers, etc.)

Do you have:
* example usage of this somewhere, e.g., in scripts on Github?
* recommendations of when / how to send each (clock and code) as commands to `sendmidi`?
* maybe additional codes that should be sent in support of this? (beginning of song?)
* any other thoughts/wisdom you have to share on the topic?

Thanks!

**Comment by gbevin** [comment]
Currently `sendmidi` only support MIDI clock by sending out a series of clock messages to allow clock sync on the receiving one to change BPM, or by sending a single MIDI clock signal itself.

Getting a steady MIDI clock generated is notoriously difficult and usually you want all your other MIDI messages to be generated by the same source to ensure that tempo changes occur at the right time.

If you don't allow tempo changes inside your sequence, you can just use `sendmidi clock <bpm>` at the beginning and it will generate what is necessary for the clock to be synced on the other end. If you do allow tempo changes, then this becomes much more tricky to coordinate with sending notes because there's no way to indicate to `sendmidi` that messages should be generates in parallel.

It just occurred to me that you could use the `sendmidi` timestamp format `HH:MM:SS.MIL` in order to schedule this out (prepending `+` allow the specification of intervals between messages). The single midi clock command is `mc` and MIDI clock is generated as 24 pulses per quarter note. This should allow you to do the math and generate the appropriate `mc` messages at the right time, alongside the other MIDI message.

Hope this helps.

**Comment by oubiwann** [comment]
Perfect! Your last paragraph was where my gut was headed ... but I wasn't sure `sendmidi` was equipped to handle a continuous stream of commands in small fractions of a second. 

What I'm thinking is essentially having a function that is dedicated to 1) checking for the current bpm, and 2) sending a `mc` message with the right timestamp (after maths). It would run async and write to the open `stdin` of `sendmidi`. Then, the functions that were responsible for sending the actual notes at any given time would do their own thing, not having to worry about the timing ...

Based upon your notes in the help text and your comment above, it sounds like `sendmidi` should be able to handle that :-) 

Time to experiment!

**Comment by ho-ho-ho** [comment]
@gbevin Speaking of `sendmidi clock` ... is there any reason for sending 49 instead of 48 midi clock messages? That kinda catched me off guard today, I thought something's wrong with the midi device I was using :D

**Comment by gbevin** [comment]
@ho-ho-ho good catch, I fixed it and the repo and will be in the next release
